### ISSUE TITLE
Listagem de grupos

### ISSUE THREAD

**Issue by NicollasPrudencio** [allstack-staff/ChamadosEasyOfertas#1]
Mesmo que o agente capturado no sistema seja um membro do grupo, a listagem não mostra os grupos.

[Evidencia 1](https://streamable.com/s64dib)

**Comment by NicollasPrudencio** [comment]
Aguardando comparecimento do autor original para prosseguir.

**Comment by gatoa12** [comment]
Bom para ficar bem mais básico. A página de agentes, consta com um bug, o qual eu não consigo fazer a postagem, pois ele mesmo buga. No vídeo abaixo posso mostrar. Outro detalhe é que com isso os disparos não conseguem, não aparecem nenhum dos meus grupos, e quando clico em disparos no whatsapp, ou disparo no telegram, a aba grupo não consta nenhum, ou não deixa eu colocar lojas, no caso ah um grande problema, pois não tem como fazer postagens desse jeito.  E lembrando que seria para canais.

**Comment by NicollasPrudencio** [comment]
Tranferido pra Agentes.

**Comment by isaias-silva** [comment]
Boa noite @gatoa12 , consegue me passar seu nome de usuário no sistema?

**Comment by gatoa12** [comment]
> Boa noite@gatoa12, consegue passar seu nome de usuário no sistema?

Boa noite. O meu usuário aqui consta como Administrador.
![photo_2024-06-06_23-40-21](https://github.com/allstack-staff/ChamadosEasyOfertas/assets/171602740/06ecbc35-cdf3-4880-914b-ab931906216d)

**Comment by NicollasPrudencio** [comment]
@gatoa12 O atendente solicita as credenciais para logar no sistema.
Pode me enviar via mensagem privada suas credenciais que transfiro para ele.

**Comment by NicollasPrudencio** [comment]
Recebido as credencias. Em atendimento.

**Comment by NicollasPrudencio** [comment]
**Chamado bloqueado** até o retorno do analista com a resolução do caso.

**Comment by isaias-silva** [comment]
resolução concluída com adição de cache na extração de grupos de integrações de whatsapp: as alterações foram feitas em https://github.com/allstack-staff/N-agents/commit/bfee78a05faadde962929a92d67c9cde0e4186ff

**Comment by NicollasPrudencio** [comment]
Atendimento finalizado. Fechando chamado.
