### ISSUE TITLE
DISPARO ERRO 1000

### ISSUE THREAD

**Issue by gatoa12** [allstack-staff/ChamadosEasyOfertas#14]
![image](https://github.com/user-attachments/assets/be651031-8336-42dd-977f-602db75210be)

SEGUE UMA MARAVILHA!

- SEM ERRO ALGUM

Enviei ofertas para todos os grupos sendo enviado, imagina para quantos? 1, número maravilhoso.

![image](https://github.com/user-attachments/assets/b4b3dbd3-f153-4d66-801a-bdbdf1e04e5c)

**Comment by NicollasPrudencio** [comment]
O chamado [número 9](https://github.com/allstack-staff/ChamadosEasyOfertas/issues/9), a solução pra esse caso já está em desenvolvimento que deve finalizar hoje.

**Fechado**.
