### ISSUE TITLE
DISPAROS ERRO

### ISSUE THREAD

**Issue by gatoa12** [allstack-staff/ChamadosEasyOfertas#4]
Como podemos observar já consta com isso aqui ao selecionar tanto uma opção ou nenhuma opção. Esse erro acontece aí, tanto no telegrama quanto no whatsapp.

Quando a seleção já fica dessa forma e não consegue dar entrada para utilizar nada dele.
![342569409-8e57ff1a-e588-45a5-b778-bb898f6a2250](https://github.com/allstack-staff/ChamadosEasyOfertas/assets/171602740/bc909f73-d890-45d8-bffc-515084569dc4)

**Comment by NicollasPrudencio** [comment]
Transferido para o analista @isaias-silva. Aguarde o atendimento. 

Enquando isso, pode informar quantas vezes ja ocorreu o mesmo problema?

**Comment by NicollasPrudencio** [comment]
Em atendimento.

**Comment by gatoa12** [comment]
@NicollasPrudencio a todo momento isso acontece na plataforma.

**Comment by isaias-silva** [comment]
Boa tarde, acredito que não esteja mais ocorrendo devido ao rebuild atualizado, pode também ser alguma configuração do navegador. segue abaixo um video com os testes:

https://github.com/allstack-staff/ChamadosEasyOfertas/assets/84031593/967003cc-d89f-44e7-895d-f0613047794a

**Comment by isaias-silva** [comment]
peço que aguarde um pouco para usar a plataforma , pois estamos atualizando e implementando novas features entre hoje e sábado oque pode dificultar o acesso, estarei encerrando esse chamado.

**Comment by NicollasPrudencio** [comment]
Obrigado por reportar o bug. O problema foi resolvido, confirme evidências do analista. Fechando chamado.
