### ISSUE TITLE
AGENTES COM ERRO

### ISSUE THREAD

**Issue by gatoa12** [allstack-staff/ChamadosEasyOfertas#5]
![image](https://github.com/user-attachments/assets/2ff0914d-8b3c-4ff6-8722-3cfe21834a2f)

Na primeira imagem não se consegue conectar o whatsapp por conta do erro aí na plataforma.
Quando aperto em add integração.... esse erro aparece: "INVALID_INTEGRATION"

________________

![image](https://github.com/user-attachments/assets/0fd05ba1-1365-491d-a661-e6940f2cf436)

Na imagem dois, mesmo fazendo todos os passos do botfather não se conectar. Por fazer gravar um vídeo explicado do início como faz o bot lá para não acontecer erros, ou crie um bot e me diga o nome para resolver o mesmo.

O mesmo bot tá adicionado nos grupos e o mesmo não já estava conectado antes, depois aconteceu que não sei o que foi, o qual passou a ser desconectado (Depois que pediram acesso à plataforma) 

@NicollasPrudencio

**Comment by NicollasPrudencio** [comment]
Transferido para o analista @isaias-silva. Aguarde o atendimento.

**Comment by NicollasPrudencio** [comment]
O solicitante informa que aparentemente foi resolvido. Fechando o chamado.
