### ISSUE TITLE
ERRO NO DISPARO DAS MENSAGENS

### ISSUE THREAD

**Issue by gatoa12** [allstack-staff/ChamadosEasyOfertas#6]
Bom. 

A página de disparo está com erro, quando estou colocando para enviar mensagem com a foto do produto ela não envia, seja tanto no whatsapp quanto no telegram. 

O mesmo tá bugando meus grupos e repetindo os mesmos.

No telegram a mensagem é enviada, porém, a foto não aparece e sim a margem do link que é enviada.
No Whatsapp é o mesmo, porém não tem foto alguma e nenhuma margem do link.

A página de disparo não tem como eu agendar o dia e hora da mensagem e nem recorrência do mesmo.
A mensagem está demorando para ser enviada aos meus grupos no agendamento (Sendo que coloco para enviar de 13:30... vai enviando de 13:32. E os testes que fiz envia até antes da horas (Exemplo: coloco para agendar na tarde e logo depois ela vai ser enviada como prioridade.)

Vídeo mostrando os erros:
https://vimeo.com/994659929?share=copy

@NicollasPrudencio

**Comment by NicollasPrudencio** [comment]
> Bom.
> 
> A página de disparo está com erro, quando estou colocando para enviar mensagem com a foto do produto ela não envia, seja tanto no whatsapp quanto no telegram.

> No telegram a mensagem é enviada, porém, a foto não aparece e sim a margem do link que é enviada. No Whatsapp é o mesmo, porém não tem foto alguma e nenhuma margem do link.
> 
Em atendimento por @FabioAugustoRodrigues e @GkIgor.




> O mesmo tá bugando meus grupos e repetindo os mesmos.
@gatoa12 Pode explicar melhor com mais detalhes?


> A página de disparo não tem como eu agendar o dia e hora da mensagem e nem recorrência do mesmo. A mensagem está demorando para ser enviada aos meus grupos no agendamento (Sendo que coloco para enviar de 13:30... vai enviando de 13:32. E os testes que fiz envia até antes da horas (Exemplo: coloco para agendar na tarde e logo depois ela vai ser enviada como prioridade.)
> 
Em atendimento por @GkIgor. A primeira frase é uma feature.
